scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken
    google:
        enabled: true
        issuer: 'ForumPlanner - Symfony'
